- name: Variables
  hosts: localhost
  vars:
    course: "devops"
    Duration: "120hrs"
    trainer: "abc"
  tasks: 
  - name: print overriding  information
    vars:
     course: "Terraform"  # Task level
    ansible.builtin.debug:
      msg: "Hi we are learning {{course}} from trainer {{trainer}},Duration is {{Duration}}"
  - name: information
    vars:
     course: "Terraform"
    ansible.builtin.debug:
      msg: "Hi we are learning {{course}} from trainer {{trainer}},Duration is {{Duration}}"