- name: variables from files
  hosts: web
  vars_prompt: 
  - name: username
    prompt: Please enter yor username
    private: false

  - name: password
    prompt: please enter your password
    private: true
  
  tasks:
  - name: print a message
    ansible.builtin.debug:
      msg: "username is {{username}} and password is {{password}}"
