- name: print the information
  hosts: localhost
  vars:
    wishes: "Good morning from PLAY level"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: wishes
    prompt: please enter wishes
    private: false

  tasks:
  - name: vars information
    #vars:
    # wishes: "Good morning from task level"
    ansible.builtin.debug:
      msg: " hello {{wishes}} to everyone"


#1.arguments
#2. task level 
#3. 
    
