- name: conditions
  hosts: web 
  become: yes 
  tasks:
  - name: check user exists or not 
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true
  
  - name: print user information
    ansible.builtin.debug:
      msg: "user info is {{user}}"

  - name: print message
    ansible.builtin.debug:
      msg: "hello"
  