- name: variables
  hosts: localhost
  vars:
      greetings: "Hello world"
  tasks:
  - name: print a message
    ansible.builtin.debug:
      msg: "Course is {{Course | default('Ansible') }}"
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower }}"


- name: remove duplicates
  hosts: localhost
  vars: 
    numbers: [1,2,4,2,3,4,5,6,7]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max ages
  hosts: localhost
  vars: 
    ages: [34,28,54,67,52]
  tasks:
  - name: min and max age
    ansible.builtin.debug:
      msg: " min ages is {{ages | min}} and max ages is {{ages | max }}"