- name: variables
  hosts: localhost
  vars:
      greetings: "Hello world"
  tasks:
  - name: print a message
    ansible.builtin.debug:
      msg: "Course is {{Course | default('Ansible') }}"
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greetings | upper }}"

  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{greetings | lower }}"